In [5]:
#  fibonacci 

a, b = 0,1 
n = int(input("Enter the limit : "))

while a< n :
    print(a,end = " ")
    a,b = b, a+b$
    

Enter the limit : 100
0 1 1 2 3 5 8 13 21 34 55 89 

In [7]:
#  factorial 

a = 1 
n = int(input("Enter the limit : "))

for i in range(a,n+1):
    a = a*i
print(a)
    

Enter the limit : 5
120


In [8]:
#  factorial in recursion

def f(n):
    if n==1:
        return 1
    return n*f(n-1)


f(10)

3628800

In [ ]:
def Fibonacci(n): 
    if n<0: 
        print("Incorrect input") 
    # First Fibonacci number is 0 
    elif n==0: 
        return 0
    # Second Fibonacci number is 1 
    elif n==1: 
        return 1
    else: 
        return Fibonacci(n-1)+Fibonacci(n-2) 
  
# Driver Program 
Fibonacci(100)

In [2]:
# dwap example

n = int(input("Enter the number for n : "))
m = int(input("Enter the number for m : "))

def swap(n,m):
    temp = n
    n= m
    m= temp
    print("n is : ",n)
    print("m is : ",m)

swap(n,m)


Enter the number for n : 10
Enter the number for m : 20
n is :  20
m is :  10


In [13]:
import calendar 

y = int(input("Enter year : "))
m = int(input("Enter month : "))
d = int(input("Enter day : "))


print(calendar.month(y,m,3))

Enter year : 1999
Enter month : 12
Enter day : 3
       December 1999
Mon Tue Wed Thu Fri Sat Sun
          1   2   3   4   5
  6   7   8   9  10  11  12
 13  14  15  16  17  18  19
 20  21  22  23  24  25  26
 27  28  29  30  31



In [12]:
n = int(input("Input the multiplication number : "))

for i in range(1,11):
    print(n,"X",i,"=",n*i)

Input the multiplication number : 10
10 X 1 = 10
10 X 2 = 20
10 X 3 = 30
10 X 4 = 40
10 X 5 = 50
10 X 6 = 60
10 X 7 = 70
10 X 8 = 80
10 X 9 = 90
10 X 10 = 100


In [ ]:
# quadratic equation is ax^2 + bx +c
from math import sqrt

a = int(input("Enter a : " ))
b = int(input("Enter b : " ))
c = int(input("Enter c : " ))

d = b**2 - 4*a*c

r1 = (-b - sqrt(d))/2*a
r2 = (-b + sqrt(d))/2*a
print(r1)
print(r2)


In [9]:
upper = eval(input("Enter a upper limit : "))
lower = eval(input("Enter a lower limit : "))

l=[]

for i in range(lower, upper+1):
    m = 0
    temp = i
    while temp>0:
        a = temp%10
        m = m + a**3
        temp = temp//10 
        if i==m:
            l.append(m)
print(l)    

Enter a upper limit : 100
Enter a lower limit : 0
[1, 64]


In [5]:
lower = int(input("Enter lower range: "))  
upper = int(input("Enter upper range: "))  
  
for num in range(lower,upper + 1):  
    sum = 0  
    temp = num  
    while temp > 0:  
        digit = temp % 10  
        sum += digit ** 3  
        temp //= 10  
        if num == sum:
            print(num)  

Enter lower range: 0
Enter upper range: 100
1
64


In [11]:
num = int(input("Enter a number : "))

if num<0:
    print("Enter a positive number")
else :
    sum = 0
    while num>0:
        sum= sum+num
        num= num-1
    print("the sum is : ",sum)

Enter a number : 10
the sum is :  55


In [1]:
def f(n):
    if n<=1:
        return n
    else :
        return(f(n-1)+f(n-2))

hl = int(input("Enter highest limit : "))
sum = 0
while sum < hl:
    if hl<=0:
        print("Enter valid input")
    else :
        print("Fibonacci sequence : ")
        for i in range(0,hl):
            sum = f(i)
            if sum > hl:
                break
            print(sum)
    

Enter highest limit : 150
Fibonacci sequence : 
0
1
1
2
3
5
8
13
21
34
55
89
144


In [4]:
def f(n):
    if n<=1:
        return n
    else :
        return(f(n-1)+f(n-2))

hl = int(input("Enter highest limit : "))
if hl<=0:
    print("Enter valid input")
else :
    print("Fibonacci sequence : ")
    for i in range(0,hl):
        sum = f(i)
        print(sum," is at index of : ",i+1)
    

Enter highest limit : 20
Fibonacci sequence : 
0  is at index of :  1
1  is at index of :  2
1  is at index of :  3
2  is at index of :  4
3  is at index of :  5
5  is at index of :  6
8  is at index of :  7
13  is at index of :  8
21  is at index of :  9
34  is at index of :  10
55  is at index of :  11
89  is at index of :  12
144  is at index of :  13
233  is at index of :  14
377  is at index of :  15
610  is at index of :  16
987  is at index of :  17
1597  is at index of :  18
2584  is at index of :  19
4181  is at index of :  20


In [20]:
u = int(input("Enter a Upper limit : "))
l = int(input("Enter a Lower limit : "))

for n in range(l,u+1):
    if n>1:
        for i in range(2,n):
            if n%i==0:
                print("not a prime number ",n)
                break
        else :
            print("prime number ", n)
                
    else:
        if n==0:
            print("Zero ",n)
        else:
            print(n," : prime number")

Enter a Upper limit : 20
Enter a Lower limit : 0
Zero  0
1  : prime number
prime number  2
prime number  3
not a prime number  4
prime number  5
not a prime number  6
prime number  7
not a prime number  8
not a prime number  9
not a prime number  10
prime number  11
not a prime number  12
prime number  13
not a prime number  14
not a prime number  15
not a prime number  16
prime number  17
not a prime number  18
prime number  19
not a prime number  20


In [15]:
for i in range(2,4):
    print(i)

2
3


In [24]:
y = int(input("Enter a year : "))

if y %4 ==0:
    if y%100==0:
        if y%400==0:
            print(y," is a leap year")
        else :
            print(y," not a leap year")
    else:
        print(y," is a leap year")
else:
    print(y," not a leap year")

Enter a year : 2020
2020  is a leap year


In [32]:
n = int(input("Enter the number one : "))
m = int(input("Enter the number two : "))

def lcm(n,m):
    if (n>m):
        g=n
    else:
        g=m
    while True:
        if (g%n==0) and (g%m==0) :
            lc = g
            break
        g =g+1
    return lc

lcm(n,m)   

Enter the number one : 5
Enter the number two : 6


30

In [31]:
n = int(input("Enter the number one : "))
m = int(input("Enter the number two : "))

def hcf(n,m):
    if (n>m):
        s=m
    else:
        s=n
    for i in range(1,s+1):
        if (n%i==0) and (m%i==0) :
            hc = i
    return hc

hcf(n,m)  

Enter the number one : 30
Enter the number two : 6


6

In [63]:
n = int(input("Enter a number in decimal : "))

print("Number in octal : ",oct(n))
print("Number in hexadecimal : ",hex(n))
print("Number in binary : ",bin(n))

b = int(input("Enter a number in binary : "))
print("Number in octal : ",oct(b))
print("Number in hexadecimal : ",hex(b))
print("Number in decimal : ",int(b))

Enter a number in decimal : 10
Number in octal :  0o12
Number in hexadecimal :  0xa
Number in binary :  0b1010
Enter a number in binary : 1010
Number in octal :  0o1762
Number in hexadecimal :  0x3f2
Number in decimal :  1010


In [52]:
c = input("Enter a character : ")
print(ord(c))

Enter a character : `
96


In [56]:
c = int(input("Enter a ascii value : "))
print(chr(c))

Enter a ascii value : 65
A


In [75]:
import numpy as np

a = np.array([[1,2,3],  
       [4,5,6],  
       [7,8,9]])
b = np.array([[10,11,12],  
       [13,14,15],  
       [16,17,18]])

result = a+b
print(result)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [80]:
a = [[1,2,3],  
       [4,5,6],  
       [7,8,9]]
b = [[10,11,12],  
       [13,14,15],  
       [16,17,18]]
r = [[0,0,0],  
       [0,0,0],  
       [0,0,0]]

for i in range(len(a)):
    for j in range(len(a[i])):
        r[i][j] = a[i][j] + b[i][j]
        
for k in r:
    print(k)

[11, 13, 15]
[17, 19, 21]
[23, 25, 27]


In [90]:
a = [[1,2,3],  
       [4,5,6],  
       [7,8,9]]  
  
b = [[10,11,12],  
      [13,14,15],  
      [16,17,18]]  
  
r = [[0,0,0],  
    [0,0,0],  
    [0,0,0]] 

for i in range(len(a)):
    for j in range(len(a[i])):
        for k in range(len(b)):
            r[i][j] += a[i][k]*b[k][j]
            
            
for l in r:
    print(l)

[84, 90, 96]
[201, 216, 231]
[318, 342, 366]


In [95]:
b = [[10,11,12],  
      [13,14,15],  
      [16,17,18]]
r = [[0,0,0],  
    [0,0,0],  
    [0,0,0]] 

for i in range(len(b)):
    for j in range(len(b[i])):
        r[i][j]= b[j][i]

for k in r:
    print(k)

[10, 13, 16]
[11, 14, 17]
[12, 15, 18]


In [98]:
i = str(input("Enter a line or character : "))

words = i.split()

words.sort()
for j in  words:
    print(j)

Enter a line or character : my name is nayeem
is
my
name
nayeem


In [107]:
from string import punctuation
s = str(input("Enter a string : "))
again=""

for i in s:
    if i not in punctuation:
        again=again+i
    else:
        again = again+" "
    
print(again)
        
    

Enter a string : i am nayem.and i am good!how about you?
i am nayem and i am good how about you 


In [103]:
# define punctuation  
punctuation = '''''!()-[]{};:'"\,<>./?@#$%^&*_~'''  
# take input from the user  
my_str = input("Enter a string: ")  
# remove punctuation from the string  
no_punct = ""  
for char in my_str:  
    if char not in punctuation:  
        no_punct = no_punct + char  
# display the unpunctuated string  
print(no_punct) 

Enter a string: i am nayem.and i am good!how about you?
i am nayemand i am goodhow about you


In [110]:
a = [1,2,3,4,5,6]
new = []
for i in range(len(a)):
    new.append(a[i])
print(new)
print(a)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]


In [122]:
a = [1,2,3,4,5,6]
r=[]
for w in range(len(a)):
    r.append(0)
    
print("The elements of original array a is : ")
for i in range(len(a)):
    print(a[i],end =' ')
p=len(a)   
for j in range(len(a)):
    r[j] = a[p-(j+1)]
    
print() 
for k in r:
    print(k,end=" ")

The elements of original array a is : 
1 2 3 4 5 6 
6 5 4 3 2 1 

In [130]:
a = [4,5,3,77,2]

for i in range(len(a)):
    print(a[i],end=" ")
print()   
print("After descending order : ")

for i in range(len(a)):
    for j in range(i+1,len(a)):
        if a[i]<a[j]:
            temp =a[i]
            a[i]=a[j]
            a[j]=temp
print(a)
        

4 5 3 77 2 
After descending order : 
[77, 5, 4, 3, 2]


In [131]:
a = [4,5,3,77,2]

for i in range(len(a)):
    print(a[i],end=" ")
print()   
print("After ascending order : ")

for i in range(len(a)):
    for j in range(i+1,len(a)):
        if a[i]>a[j]:
            temp =a[i]
            a[i]=a[j]
            a[j]=temp
print(a)

4 5 3 77 2 
After ascending order : 
[2, 3, 4, 5, 77]


In [161]:

a = [4,5,3,77,2,22,3,66,77]
nd =[]
dup=[]
print("The original array A is :")
for i in range(len(a)):
    print(a[i],end=" ")
    
print()

for j in range(len(a)):
    for k in range(j+1,len(a)):
        if a[j] == a[k]:
            dup.append(a[j])
    if a[j] not in dup:
        nd.append(a[j])
            

    
print("Non Duplicates: ",nd)
print("Duplicates :",dup)

The original array A is :
4 5 3 77 2 22 3 66 77 
Non Duplicates:  [4, 5, 2, 22, 66]
Duplicates : [3, 77]


In [163]:
a = [4,5,3,77,2,22,3,66,77]

for i in range(len(a)-1,-1,-1):
    print(a[i],end=" ")

77 66 3 22 2 77 3 5 4 

In [171]:
a = [4,5,3,77,2,22,3,66,77]

for i in range(1,len(a)):
    if i%2 !=0:
        print(a[i],end=" ") #even position

5 77 22 66 

In [172]:
a = [4,5,3,77,2,22,3,66,77]

for i in range(len(a)):
    if i%2 ==0:
        print(a[i],end=" ") #odd position

4 3 2 3 77 

In [173]:
a = [4,5,3,77,2,22,3,66,77]

for i in range(len(a)):
    for j in  range(i+1,len(a)):
        if a[i]<a[j]:
            temp =a[i]
            a[i]=a[j]
            a[j]=temp
print(a[0])

77


In [177]:
a = [4,5,3,77,2,22,3,66,77]
max = a[0]
for i in range(len(a)):
    if a[i]>max:
        max=a[i]
   
print(max)

77


In [178]:
a = [4,5,3,77,2,22,3,66,77]
min = a[0]
for i in range(len(a)):
    if a[i]<min:
        min=a[i]
   
print(min)

2


In [179]:
a = [4,5,3,77,2,22,3,66,77]
sum =0

for i in range(len(a)):
    sum = sum+a[i]
print(sum)

259


In [ ]:
#  frequency, left rotate and right rotate

In [ ]:
n = int(input("Enter a number : "))

while 